/**
 * Created by mgobbi on 01/12/2016.
 */
var cibo = {
    "abbigliamento": "Abbigliamento",
    "accessori": "Accessori",
    "agenzia_viaggio": "Agenzia Viaggio",
    "agricultura": "Agricultura",
    "alimentari": "Alimentari",
    "arte_intrattenimento": "Arte & Intrattenimento",
    "bar": "Bar",
    "bar_sport": "Bar dello Sport",
    "beach": "Spiaggia",
    "bed_and_breakfast": "Bed & Breakfast",
    "benessere": "Benessere",
    "buffet": "Buffet",
    "cartoleria": "Cartoleria",
    "catering": "Catering",
    "cinema": "Cinema",
    "circus": "Circo",
    "clubhouse": "Club",
    "colazioni_brunch": "Colazioni & Brunch",
    "community & government": "Community & Government",
    "da_asporto": "Cibo da Asporto",
    "dance club": "Sala da Ballo",
    "educazione_istruzione": "educazione_istruzione",
    "enoteca": "Enoteca",
    "event_planner": "Organizzatore di Eventi",
    "fast_food": "Fast Food",
    "food & beverage": "Panini & Bibite",
    "food stand": "Chiosco",
    "full gospel church": "Chiesa Gospel",
    "funeral service": "Onoranze Funebri",
    "garden center": "Giardino",
    "gelateria": "Gelateria",
    "gruppo_musicale": "Gruppo Musicale",
    "hamburger": "Hamburger",
    "health": "Salute",
    "hindu temple": "Tempio Hindu",
    "hotel": "Hotel",
    "junior high school": "Scuola Elementare",
    "luogo_interesse": "Luogo di Interesse",
    "musica": "Musica",
    "negozio": "Negozio",
    "palestra": "Palestra",
    "panini": "Panini",
    "piadineria": "Piadineria",
    "piccola_ristorazione": "Piccola Ristorazione",
    "pizzeria": "Pizzeria",
    "playground": "playground",
    "public services & government": "Servizio Pubblico",
    "public square": "Piazza",
    "residence": "Residence",
    "ristorante_brasiliano": "Ristorante Brasiliano",
    "ristorante_cinese": "Ristorante Cinese",
    "ristorante_europeo": "Ristorante Europeo",
    "ristorante_famiglie": "Ristorante per Famiglie",
    "ristorante_greco": "Ristorante Greco",
    "ristorante_italiano": "Ristorante Italiano",
    "ristorante_mediterraneo": "Ristorante _Mediterraneo",
    "ristorante_pesce": "Ristorante di Pesce",
    "ristorante_tex_mex": "Ristorante Tex Mex",
    "ristorante_thai": "Ristorante Thai",
    "ristoranti": "Ristoranti",
    "river": "Fiume",
    "scuola": "Scuola",
    "shopping/retail": "shopping/retail",
    "sports": "Sports",
    "sushi": "Sushi",
    "vegetarian_vegan restaurant": "Ristorante Vegetariano Vegano",
    "vegetariano": "Vegetariano",
    "workplace & office": "Workplace & Ufficio",
    "cibo": "Cibo",
    "teatro": "Teatro",
    //
    "city": "Città",
    "dvd & video store": "Negozio di DVD & Video",
    "mission": "Mission",
    "obgyn": "Obgyn",
    "organizzazione_no_profit": "Organizzazione no Profit",
    "ospedale": "Ospedale",
    "ottica": "Ottica",
//
    "abbigliamento_bambino": "Abbigliamento Bambino",
    "cleaning service": "Servizio di Pulizie",
    "erboristeria": "Erboristeria",
    "farmacia": "Farmacia",
    "food consultant": "Consulente Alimentare",
    "gioielleria": "Gioielleria",
    "health/medical/pharmaceuticals": "health/medical/pharmaceuticals",
    "image consultant": "Consulente di Immagine",
    "massaggi": "Massaggi",
    "medical & health": "Salute e Benessere",
    "medicina": "Medicina",
    "nail salon": "Salone per Unghie",
    "parrucchiera": "Parrucchiera",
    "party center": "Party Center",
    "tanning salon": "Salone Abbronzature",
    "wig store": "Negozio di Parrucche",
    //
    "abbigliamento_donna": "Abbigliamento Donna",
    "abbigliamento_uomo": "Abbigliamento Uomo",
    "architettura": "Architettura",
    "arredamento": "Arredamento",
    "arts & crafts supply store": "Arts & Crafts Supply Store",
    "automobili": "Automobili",
    "automotive repair": "Riparazioni Automobili",
    "awnings & canopies": "Tende & Tettoie",
    "bicicletta": "Bicicletta",
    "car_rental": "Noleggio Auto",
    "casalinghi": "Casalinghi",
    "company": "Società",
    "computer_elettronica": "Computer ed Elettronica",
    "consulenze_finanziarie": "Consulenze Finanziarie",
    "electrician": "Elettricista",
    "ferramenta": "Ferramenta",
    "fiorista_vivaio": "Fiorista Vivaio",
    "general_contractor": "Appaltatore",
    "giardinaggio": "Giardinaggio",
    "home": "Casa",
    "hotel supply service": "Forniura Hotel",
    "libreria": "Libreria",
    "negozio_musica": "Negozio di Musica",
    "negozio_sportivo": "Negozio Sportivo",
    "other": "Altro",
    "parco": "Parco",
    "patrol & security": "Sicurezza",
    "riparazioni": "Riparazioni",
    "sartoria": "Sartoria",
    "scarpe": "Scarpe",
    "smartphone": "Smartphone",
    "sposa": "Sposa",
    "supermercato": "Supermercato",
    "thrift or consignment store": "Negozio di Spedizioni",
    "toy store": "Negozio di Giocattoli",
//
    "biblioteca": "Biblioteca",
    "centro_ricreativo": "Centro Ricreativo",
    "day care": "Day Care",
    "internet/software": "Internet & Software",
    "preschool": "Asilo",
    "prison & correctional facility": "Istituti Correzionali",
    "public service": "Servizi Pubblici ",
    "scuola_musica": "Scuola di Musica",
    "social services": "Social Services",
    "ufficio_pubblico": "Ufficio Pubblico",
    "universita": "Universita",
    "agency": "Agenzia",
    "biotechnology": "Biotechnologia",
    "computers/technology": "Computers & Technologia",
    "market research consultant": "Consulente Marketing",
    "photographer": "Fotografo",
    "publisher": "Editore",
    "web_design": "Web Design",
    "fashion designer": "Fashion Designer",
    "graphic_design": "Graphic Design",
//
    "tours & sightseeing": "Tours Guidati",
    "travel & transportation": "Viaggio & Trasporti",
//
    "frutta_verdura": "Frutta & Verdura",
    "bridge": "Ponte",
    "catholic church": "Chiesa Cattolica",
    "event": "Evento",
    "museo": "Museo",
    "posti_storici": "Posti Storici"
    ,
    "child protective service": "child protective service"
    ,
    "climbing": "climbing",


    "arti_marziali": "arti_marziali",
    "bingo hall": "bingo hall",
    "club_sportivo": "club_sportivo",
    "community organization": "community organization",
    "event venue": "event venue",
    "lottery retailer": "lottery retailer",
    "occupational therapist": "occupational therapist",
    "personal_trainer": "personal_trainer",
    "piscina": "piscina",
    "stadio": "stadio",
    "tennis": "tennis",
    "yoga_pilates": "yoga_pilates",
    //
    "church": "church",
    "collectibles store": "collectibles store",
    "cultural gifts store": "cultural gifts store",
    "fumetteria": "fumetteria",
    //
    "assicurazioni": "assicurazioni",
    "avvocato": "avvocato",
    "banca": "banca",
    "bank/financial institution": "bank/financial institution",
    "big box retailer": "big box retailer",
    "estate planning": "estate planning",
    "financial aid": "financial aid",
    "financial service": "financial service",
    "gas_station": "gas_station",
    "insurance company": "insurance company",
    "passport & visa service": "passport & visa service",
    "post office": "post office",
    "post_office": "post_office",
    "real_estate": "real_estate",
    "refrigeration": "refrigeration",
    "tech": "tech",
    "wholesale & supply store": "wholesale & supply store",
    "produzione_musicale": "produzione_musicale",

    //
    "audiovisual equipment": "audiovisual equipment",
    "just for fun": "just for fun",
    "neighborhood": "neighborhood",
    "rental shop": "rental shop",
    //
    "congregational church": "congregational church",
    "place_of_worship": "place_of_worship",
    "religious organization": "religious organization",
    //
    "art gallery": "art gallery",
    "home improvement": "home improvement",
    //
    "real estate developer": "real estate developer",
    //
    "automation service": "automation service",
    "environmental consultant": "environmental consultant",
    "funeral_home": "funeral_home",
    "home security": "home security",
    //
    "apartment & condo building": "apartment & condo building",
    //
    "heating, ventilating & air conditioning": "heating, ventilating & air conditioning",
    "plumber": "plumber",
    //
    "car rental": "car rental",
    //
    "adoption service": "adoption service",
    "animal shelter": "animal shelter",
    "charity organization": "charity organization",
    //
    "printing service": "printing service",


}


module.exports = cibo;